### ISSUE TITLE
CSS 控制图片最短边 按比例缩放

### ISSUE THREAD

**Issue by HAAAAADION** [HAAAAADION/blog#12]
```css
// background-size: cover;
.test {
    background: url('your img link');
    background-size: cover;
}

// object-fit: cover;
//直接设置在<img />标签
img {
    object-fit: cover;
    width: 100px;
    height: 100px;
}
```
参考: [object-fit: cover;](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)
